import Head from 'next/head';
import { authentication } from '../firebase';
import { signInWithPopup, GoogleAuthProvider } from 'firebase/auth';
import { useRouter } from 'next/router';

export default function Home() {
	const router = useRouter();

	const signInWithGoogle = () => {
		const provider = new GoogleAuthProvider();
		signInWithPopup(authentication, provider)
			.then((result) => {
				console.log(result);
				router.push('/Home');
			})
			.catch((error) => {
				console.log(error);
			});
	};
	return (
		<div>
			<Head>
				<title>Family Facebook</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/FB.ico" />
			</Head>
			<div className="flex flex-col justify-center items-center h-screen">
				<p className="flex justify-center text-3xl font-bold text-[#4267B2]">
					Family Facebook
				</p>

				<div className="flex justify-center">
					<button
						className="text-xl text-white font-bold rounded-md bg-blue-500 px-16 py-2 m-5"
						onClick={signInWithGoogle}
					>
						Login
					</button>
				</div>
			</div>
		</div>
	);
}

// work on
/*

Login Page
DONE

Home Page
comment feature
- post 
- delete 
- update
- timestamp

Profile Page 
- view other users
- displays posts
- bio
- chat

Chat Page

Connect with metamask?
*/
