import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Family Facebook</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<p className="flex justify-center text-3xl font-bold">Family Facebook</p>

			<p className="flex justify-center text-xl font-bold">Login with google</p>
		</div>
	);
}
